# SPDX-FileCopyrightText: 2025 Swiss Confederation
#
# SPDX-License-Identifier: MIT

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5280/status-registry-db"
    username: "postgres"
    password: "secret"
  docker:
    compose:
      enabled: true
      file: compose.yml

security:
  oauth2:
    jwt:
      issuer-uris:
        dev-issuer: https://auth-d.trust-infra.swiyu.admin.ch/realms/bj-swiyu-ecosystem
        ref-issuer: https://auth-r.trust-infra.swiyu.admin.ch/realms/bj-swiyu-ecosystem-portal-scs

status-registry:
  dataUrlTemplate: "http://localhost:8290/api/v1/statuslist/{0}.{1}"
  authoringBaseUrl: "http://localhost:8280/"

